// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU3m11pSSKyJ64G6Ktqns7vZimdTl9t0A',
    appId: '1:807258740773:android:abff1bf773f61b14f047cc',
    messagingSenderId: '807258740773',
    projectId: 'mynotes8017',
    storageBucket: 'mynotes8017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwZNNW9UR69MmpXXNgV-eNttACkCGauzE',
    appId: '1:807258740773:ios:a12d5fe202124115f047cc',
    messagingSenderId: '807258740773',
    projectId: 'mynotes8017',
    storageBucket: 'mynotes8017.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAefFlmF12sl6LEVWRnOJiFHGcBfesy67U',
    appId: '1:807258740773:web:5fc6662386d591d1f047cc',
    messagingSenderId: '807258740773',
    projectId: 'mynotes8017',
    authDomain: 'mynotes8017.firebaseapp.com',
    storageBucket: 'mynotes8017.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwZNNW9UR69MmpXXNgV-eNttACkCGauzE',
    appId: '1:807258740773:ios:a12d5fe202124115f047cc',
    messagingSenderId: '807258740773',
    projectId: 'mynotes8017',
    storageBucket: 'mynotes8017.appspot.com',
    iosBundleId: 'com.example.myFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAefFlmF12sl6LEVWRnOJiFHGcBfesy67U',
    appId: '1:807258740773:web:d3b180b0c615fa82f047cc',
    messagingSenderId: '807258740773',
    projectId: 'mynotes8017',
    authDomain: 'mynotes8017.firebaseapp.com',
    storageBucket: 'mynotes8017.appspot.com',
  );

}